### ISSUE TITLE
Flextools dependency

### ISSUE THREAD

**Issue by MattGyverLee** [cdfarrow/cdfutils#3]
FLEXTools recommends Python 3.8, which is no longer supported (neither is 3.9).
FLExTools depends on CDFutils. 
CDFUtils expects 3.6-3.9 (but not 3.10).

Currently, a Windows user can't install a viable version of Python (3.8-3.9) for FLExTools without building Python from source (or getting a binary from another source such as https://github.com/adang1345/PythonWindows). 

Please update CDFTools to support 3.10.

**Comment by cdfarrow** [comment]
Thanks for your query, but cdfutils supports Python 3.10, and that is listed on the [PyPI page](https://pypi.org/project/cdfutils/). Is there somewhere where it says 3.10 is excluded for _cdfutils_?

**Comment by MattGyverLee** [comment]
Understood. Closing the issue.
